// 左侧菜单数据
const menu = [
  {
    menuId: 1,
    menuName: "推荐",
    menuIcon: "android",
    menuTagsId: "未设置",
    menuSort: 1,
    menuTypeId: "0",
    menuStatus: "0",
    updateTime: "2021-08-01 21:43:53",
    createTime: "2021-08-01 21:43:55",
    type: null,
    tags: [
      {
        tagsId: 1,
        tagsName: "最新",
        tagsColor: null,
        tagsIcon: null,
        tagsSort: 1,
        tagsMenuId: "1,2,3,",
        tagsClassifyId: "1,2,3,",
        tagsStatus: "0",
        updateTime: "2021-08-03 23:22:54",
        createTime: null,
      },
      {
        tagsId: 2,
        tagsName: "推荐",
        tagsColor: null,
        tagsIcon: null,
        tagsSort: 2,
        tagsMenuId: "1,2,",
        tagsClassifyId: "1,",
        tagsStatus: "0",
        updateTime: null,
        createTime: null,
      },
      {
        tagsId: 3,
        tagsName: "优秀",
        tagsColor: null,
        tagsIcon: null,
        tagsSort: 3,
        tagsMenuId: "1,",
        tagsClassifyId: "1,",
        tagsStatus: "0",
        updateTime: null,
        createTime: null,
      },
      {
        tagsId: 4,
        tagsName: "测试",
        tagsColor: null,
        tagsIcon: null,
        tagsSort: 4,
        tagsMenuId: "1,2,",
        tagsClassifyId: "1,",
        tagsStatus: "0",
        updateTime: null,
        createTime: null,
      },
    ],
  },
  {
    menuId: 2,
    menuName: "电脑APP",
    menuIcon: "windows",
    menuTagsId: "未设置",
    menuSort: 2,
    menuTypeId: "1",
    menuStatus: "0",
    updateTime: "2021-08-01 21:43:59",
    createTime: "2021-08-01 21:44:02",
    type: null,
    tags: [
      {
        tagsId: 1,
        tagsName: "最新",
        tagsColor: null,
        tagsIcon: null,
        tagsSort: 1,
        tagsMenuId: "1,2,3,",
        tagsClassifyId: "1,2,3,",
        tagsStatus: "0",
        updateTime: "2021-08-03 23:22:54",
        createTime: null,
      },
      {
        tagsId: 2,
        tagsName: "推荐",
        tagsColor: null,
        tagsIcon: null,
        tagsSort: 2,
        tagsMenuId: "1,2,",
        tagsClassifyId: "1,",
        tagsStatus: "0",
        updateTime: null,
        createTime: null,
      },
      {
        tagsId: 4,
        tagsName: "测试",
        tagsColor: null,
        tagsIcon: null,
        tagsSort: 4,
        tagsMenuId: "1,2,",
        tagsClassifyId: "1,",
        tagsStatus: "0",
        updateTime: null,
        createTime: null,
      },
    ],
  },
  {
    menuId: 3,
    menuName: "测试",
    menuIcon: "apple",
    menuTagsId: "未设置",
    menuSort: 3,
    menuTypeId: "0",
    menuStatus: "0",
    updateTime: "2021-08-01 21:43:25",
    createTime: "2021-08-01 21:43:25",
    type: null,
    tags: [
      {
        tagsId: 1,
        tagsName: "最新",
        tagsColor: null,
        tagsIcon: null,
        tagsSort: 1,
        tagsMenuId: "1,2,3,",
        tagsClassifyId: "1,2,3,",
        tagsStatus: "0",
        updateTime: "2021-08-03 23:22:54",
        createTime: null,
      },
    ],
  },
  {
    menuId: 4,
    menuName: "测试2",
    menuIcon: "chrome",
    menuTagsId: "未设置",
    menuSort: 4,
    menuTypeId: "1",
    menuStatus: "0",
    updateTime: "2021-08-03 23:35:51",
    createTime: null,
    type: null,
    tags: [],
  },
];

export default {
    menu,
};
